DELETE FROM country;

INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(1, 'Afghanistan', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(2, 'Albania', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(3, 'Algeria', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(4, 'American Samoa', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(5, 'Andorra', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(6, 'Angola', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(7, 'Anguilla', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(8, 'Antarctica', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(9, 'Antigua and Barbuda', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(10, 'Argentina', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(11, 'Armenia', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(12, 'Aruba', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(13, 'Australia', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(14, 'Austria', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(15, 'Azerbaijan', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(16, 'Bahamas', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(17, 'Bahrain', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(18, 'Bangladesh', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(19, 'Barbados', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(20, 'Belarus', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(21, 'Belgium', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(22, 'Belize', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(23, 'Benin', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(24, 'Bermuda', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(25, 'Bhutan', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(26, 'Bolivia', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(27, 'Bosnia and Herzegovina', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(28, 'Botswana', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(29, 'Bouvet Island', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(30, 'Brazil', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(31, 'British Indian Ocean Territory', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(32, 'Brunei Darussalam', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(33, 'Bulgaria', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(34, 'Burkina Faso', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(35, 'Burundi', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(36, 'Cambodia', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(37, 'Cameroon', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(38, 'Canada', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(39, 'Cape Verde', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(40, 'Cayman Islands', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(41, 'Central African Republic', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(42, 'Chad', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(43, 'Chile', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(44, 'China', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(45, 'Christmas Island', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(46, 'Cocos (Keeling) Islands', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(47, 'Colombia', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(48, 'Comoros', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(49, 'Congo', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(50, 'Congo, the Democratic Republic of the', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(51, 'Cook Islands', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(52, 'Costa Rica', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(53, 'Cote D\'Ivoire', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(54, 'Croatia', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(55, 'Cuba', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(56, 'Cyprus', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(57, 'Czech Republic', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(58, 'Denmark', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(59, 'Djibouti', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(60, 'Dominica', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(61, 'Dominican Republic', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(62, 'Ecuador', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(63, 'Egypt', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(64, 'El Salvador', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(65, 'Equatorial Guinea', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(66, 'Eritrea', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(67, 'Estonia', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(68, 'Ethiopia', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(69, 'Falkland Islands (Malvinas)', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(70, 'Faroe Islands', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(71, 'Fiji', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(72, 'Finland', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(73, 'France', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(74, 'French Guiana', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(75, 'French Polynesia', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(76, 'French Southern Territories', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(77, 'Gabon', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(78, 'Gambia', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(79, 'Georgia', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(80, 'Germany', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(81, 'Ghana', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(82, 'Gibraltar', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(83, 'Greece', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(84, 'Greenland', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(85, 'Grenada', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(86, 'Guadeloupe', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(87, 'Guam', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(88, 'Guatemala', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(89, 'Guinea', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(90, 'Guinea-Bissau', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(91, 'Guyana', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(92, 'Haiti', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(93, 'Heard Island and Mcdonald Islands', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(94, 'Holy See (Vatican City State)', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(95, 'Honduras', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(96, 'Hong Kong', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(97, 'Hungary', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(98, 'Iceland', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(99, 'India', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(100, 'Indonesia', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(101, 'Iran, Islamic Republic of', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(102, 'Iraq', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(103, 'Ireland', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(104, 'Israel', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(105, 'Italy', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(106, 'Jamaica', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(107, 'Japan', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(108, 'Jordan', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(109, 'Kazakhstan', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(110, 'Kenya', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(111, 'Kiribati', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(112, 'Korea, Democratic People\'s Republic of', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(113, 'Korea, Republic of', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(114, 'Kuwait', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(115, 'Kyrgyzstan', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(116, 'Lao People\'s Democratic Republic', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(117, 'Latvia', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(118, 'Lebanon', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(119, 'Lesotho', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(120, 'Liberia', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(121, 'Libyan Arab Jamahiriya', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(122, 'Liechtenstein', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(123, 'Lithuania', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(124, 'Luxembourg', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(125, 'Macao', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(126, 'Macedonia, the Former Yugoslav Republic of', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(127, 'Madagascar', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(128, 'Malawi', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(129, 'Malaysia', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(130, 'Maldives', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(131, 'Mali', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(132, 'Malta', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(133, 'Marshall Islands', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(134, 'Martinique', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(135, 'Mauritania', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(136, 'Mauritius', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(137, 'Mayotte', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(138, 'Mexico', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(139, 'Micronesia, Federated States of', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(140, 'Moldova, Republic of', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(141, 'Monaco', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(142, 'Mongolia', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(143, 'Montserrat', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(144, 'Morocco', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(145, 'Mozambique', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(146, 'Myanmar', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(147, 'Namibia', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(148, 'Nauru', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(149, 'Nepal', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(150, 'Netherlands', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(151, 'Netherlands Antilles', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(152, 'New Caledonia', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(153, 'New Zealand', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(154, 'Nicaragua', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(155, 'Niger', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(156, 'Nigeria', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(157, 'Niue', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(158, 'Norfolk Island', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(159, 'Northern Mariana Islands', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(160, 'Norway', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(161, 'Oman', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(162, 'Pakistan', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(163, 'Palau', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(164, 'Palestinian Territory, Occupied', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(165, 'Panama', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(166, 'Papua New Guinea', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(167, 'Paraguay', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(168, 'Peru', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(169, 'Philippines', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(170, 'Pitcairn', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(171, 'Poland', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(172, 'Portugal', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(173, 'Puerto Rico', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(174, 'Qatar', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(175, 'Reunion', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(176, 'Romania', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(177, 'Russian Federation', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(178, 'Rwanda', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(179, 'Saint Helena', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(180, 'Saint Kitts and Nevis', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(181, 'Saint Lucia', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(182, 'Saint Pierre and Miquelon', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(183, 'Saint Vincent and the Grenadines', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(184, 'Samoa', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(185, 'San Marino', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(186, 'Sao Tome and Principe', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(187, 'Saudi Arabia', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(188, 'Senegal', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(189, 'Serbia and Montenegro', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(190, 'Seychelles', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(191, 'Sierra Leone', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(192, 'Singapore', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(193, 'Slovakia', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(194, 'Slovenia', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(195, 'Solomon Islands', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(196, 'Somalia', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(197, 'South Africa', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(198, 'South Georgia and the South Sandwich Islands', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(199, 'Spain', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(200, 'Sri Lanka', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(201, 'Sudan', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(202, 'Suriname', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(203, 'Svalbard and Jan Mayen', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(204, 'Swaziland', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(205, 'Sweden', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(206, 'Switzerland', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(207, 'Syrian Arab Republic', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(208, 'Taiwan, Province of China', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(209, 'Tajikistan', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(210, 'Tanzania, United Republic of', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(211, 'Thailand', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(212, 'Timor-Leste', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(213, 'Togo', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(214, 'Tokelau', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(215, 'Tonga', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(216, 'Trinidad and Tobago', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(217, 'Tunisia', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(218, 'Turkey', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(219, 'Turkmenistan', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(220, 'Turks and Caicos Islands', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(221, 'Tuvalu', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(222, 'Uganda', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(223, 'Ukraine', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(224, 'United Arab Emirates', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(225, 'United Kingdom', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(226, 'United States', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(227, 'United States Minor Outlying Islands', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(228, 'Uruguay', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(229, 'Uzbekistan', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(230, 'Vanuatu', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(231, 'Venezuela', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(232, 'Viet Nam', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(233, 'Virgin Islands, British', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(234, 'Virgin Islands, U.s.', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(235, 'Wallis and Futuna', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(236, 'Western Sahara', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(237, 'Yemen', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(238, 'Zambia', 1, NOW(), 1, NOW());
INSERT INTO country(country_id, name, create_user, create_date, last_update_user, last_update_date) VALUES(239, 'Zimbabwe', 1, NOW(), 1, NOW());

DELETE FROM role;

INSERT INTO role(role_id, name, description, create_user, create_date, last_update_user, last_update_date) VALUES(1, 'Anonymous', 'The privileges anonymous user poccesses.', 1, NOW(), 1, NOW());

DELETE FROM permission_level;

INSERT INTO permission_level(permission_level_id, description, create_user, create_date, last_update_user, last_update_date) VALUES(1, 'View', 1, NOW(), 1, NOW());
INSERT INTO permission_level(permission_level_id, description, create_user, create_date, last_update_user, last_update_date) VALUES(2, 'Participate', 1, NOW(), 1, NOW());
INSERT INTO permission_level(permission_level_id, description, create_user, create_date, last_update_user, last_update_date) VALUES(3, 'Admin', 1, NOW(), 1, NOW());

DELETE FROM limits;

INSERT INTO limits(limits_id, time_limit, memory_limit, output_limit, submission_limit) VALUES(1, 1, 32768, 32768, 32);

DELETE FROM reference_type;

INSERT INTO reference_type(reference_type_id, description, create_user, create_date, last_update_user, last_update_date) VALUES(1, 'Description', 1, NOW(), 1, NOW());
INSERT INTO reference_type(reference_type_id, description, create_user, create_date, last_update_user, last_update_date) VALUES(2, 'Input', 1, NOW(), 1, NOW());
INSERT INTO reference_type(reference_type_id, description, create_user, create_date, last_update_user, last_update_date) VALUES(3, 'Output', 1, NOW(), 1, NOW());
INSERT INTO reference_type(reference_type_id, description, create_user, create_date, last_update_user, last_update_date) VALUES(4, 'Auxiliary', 1, NOW(), 1, NOW());
INSERT INTO reference_type(reference_type_id, description, create_user, create_date, last_update_user, last_update_date) VALUES(5, 'Checker', 1, NOW(), 1, NOW());
INSERT INTO reference_type(reference_type_id, description, create_user, create_date, last_update_user, last_update_date) VALUES(6, 'Checker Source', 1, NOW(), 1, NOW());
INSERT INTO reference_type(reference_type_id, description, create_user, create_date, last_update_user, last_update_date) VALUES(7, 'Judge Solution', 1, NOW(), 1, NOW());
INSERT INTO reference_type(reference_type_id, description, create_user, create_date, last_update_user, last_update_date) VALUES(8, 'Download', 1, NOW(), 1, NOW());
INSERT INTO reference_type(reference_type_id, description, create_user, create_date, last_update_user, last_update_date) VALUES(9, 'Misc', 1, NOW(), 1, NOW());

DELETE FROM configuration;
