ALTER DATABASE zoj DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

ALTER TABLE country DEFAULT CHARACTER SET utf8 COLLATE utf8_bin; 
ALTER TABLE user_profile DEFAULT CHARACTER SET utf8 COLLATE utf8_bin; 
ALTER TABLE user_preference DEFAULT CHARACTER SET utf8 COLLATE utf8_bin; 
ALTER TABLE confirmation DEFAULT CHARACTER SET utf8 COLLATE utf8_bin; 
ALTER TABLE role DEFAULT CHARACTER SET utf8 COLLATE utf8_bin; 
ALTER TABLE user_role DEFAULT CHARACTER SET utf8 COLLATE utf8_bin; 
ALTER TABLE contest_permission DEFAULT CHARACTER SET utf8 COLLATE utf8_bin; 
ALTER TABLE forum_permission DEFAULT CHARACTER SET utf8 COLLATE utf8_bin; 
ALTER TABLE permission_level DEFAULT CHARACTER SET utf8 COLLATE utf8_bin; 
ALTER TABLE contest DEFAULT CHARACTER SET utf8 COLLATE utf8_bin; 
ALTER TABLE language DEFAULT CHARACTER SET utf8 COLLATE utf8_bin; 
ALTER TABLE contest_language DEFAULT CHARACTER SET utf8 COLLATE utf8_bin; 
ALTER TABLE limits DEFAULT CHARACTER SET utf8 COLLATE utf8_bin; 
ALTER TABLE problem DEFAULT CHARACTER SET utf8 COLLATE utf8_bin; 
ALTER TABLE submission DEFAULT CHARACTER SET utf8 COLLATE utf8_bin; 
ALTER TABLE judge_reply DEFAULT CHARACTER SET utf8 COLLATE utf8_bin; 
ALTER TABLE forumDEFAULT CHARACTER SET utf8 COLLATE utf8_bin; 
ALTER TABLE thread DEFAULT CHARACTER SET utf8 COLLATE utf8_bin; 
ALTER TABLE post DEFAULT CHARACTER SET utf8 COLLATE utf8_bin; 
ALTER TABLE referenceDEFAULT CHARACTER SET utf8 COLLATE utf8_bin; 
ALTER TABLE reference_typeDEFAULT CHARACTER SET utf8 COLLATE utf8_bin; 
ALTER TABLE contest_referenceDEFAULT CHARACTER SET utf8 COLLATE utf8_bin; 
ALTER TABLE problem_referenceDEFAULT CHARACTER SET utf8 COLLATE utf8_bin; 
ALTER TABLE forum_reference DEFAULT CHARACTER SET utf8 COLLATE utf8_bin; 
ALTER TABLE configurationDEFAULT CHARACTER SET utf8 COLLATE utf8_bin; 

