/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.edu.zju.acm.onlinejudge.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import cn.edu.zju.acm.onlinejudge.bean.Problem;
import cn.edu.zju.acm.onlinejudge.util.ContestManager;
import cn.edu.zju.acm.onlinejudge.util.ContestStatistics;
import cn.edu.zju.acm.onlinejudge.util.PersistenceManager;
import cn.edu.zju.acm.onlinejudge.util.ProblemStatistics;
import cn.edu.zju.acm.onlinejudge.util.StatisticsManager;
import cn.edu.zju.acm.onlinejudge.util.Utility;

/** 
 * MyEclipse Struts
 * Creation date: 07-27-2008
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="/show_problem_status.jsp"
 */
public class ShowProblemStatusAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form, ContextAdapter context) throws Exception {
		
		
    	// check contest
    	boolean isProblemset = context.getRequest().getRequestURI().endsWith("showProblemStatus.do");
    	
    	ActionForward forward = checkProblemViewPermission(mapping, context, isProblemset);
    	if (forward != null) {
    		return forward;
    	}    	    	
    	
    	Problem problem = context.getProblem();
    	String orderBy = context.getRequest().getParameter("orderBy");
    	if (!"date".equals(orderBy) && !"memory".equals(orderBy)) {
    		orderBy = "time";
    	}
    	if (problem != null) {
    		ProblemStatistics statistics = StatisticsManager.getInstance().getProblemStatistics(problem.getId(), orderBy, 20);
    		context.setAttribute("ProblemStatistics", statistics);
    		
    	}
		
		return handleSuccess(mapping, context, "success");
	}
}