/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.edu.zju.acm.onlinejudge.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import java.io.*;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

import cn.edu.zju.acm.onlinejudge.form.ImportUserForm;
import cn.edu.zju.acm.onlinejudge.action.BaseAction;
import cn.edu.zju.acm.onlinejudge.action.ContextAdapter;
import cn.edu.zju.acm.onlinejudge.bean.UserProfile;
import cn.edu.zju.acm.onlinejudge.util.PersistenceManager;

/** 
 * MyEclipse Struts
 * Creation date: 08-21-2008
 * 
 * XDoclet definition:
 * @struts.action path="/importUser" name="importUserForm" input="/form/importUser.jsp" scope="request" validate="true"
 */
public class ImportUserAction extends BaseAction {


	@Override
	protected ActionForward execute(ActionMapping mapping, ActionForm form,
			ContextAdapter context) throws Exception {
		// TODO Auto-generated method stub
		UserProfile u = context.getUserProfile();
		long teacherId = u.getId();
		ImportUserForm importUserForm = (ImportUserForm) form;// TODO Auto-generated method stub
		FormFile users = importUserForm.getUserinfo();
		InputStreamReader isr = new InputStreamReader(users.getInputStream());
		java.io.BufferedReader br = new BufferedReader(isr);
		String user = br.readLine();

		List<String> list = new LinkedList<String>();
		while(user!=null)
		{
			String[] temp=user.split(" ");
			
			UserProfile student=new UserProfile();
			
			student.setAddressLine1("line1");
			student.setAddressLine2("line2");
			student.setHandle(temp[0]);
			student.setPassword(temp[0]);
			student.setFirstName(temp[1]);
			student.setLastName("");
			student.setEmail(new Integer(new Date().hashCode()).toString()+temp[0]);
			student.setCity("null");
			student.setState("null");
			student.setBirthDate(new Date());
			student.setCountry(PersistenceManager.getInstance().getCountry("44"));
			student.setZipCode("null");
			student.setPhoneNumber("null");
			student.setGender('M');
			student.setSchool("Zhejiang University");
			student.setMajor("null");
			student.setGraduateStudent(false);
			student.setGraduationYear(2010);
			student.setStudentNumber(temp[0]);  
			student.setConfirmed(true);
			PersistenceManager.getInstance().getUserPersistence().createUserProfile(student, teacherId);
			user=br.readLine();

			list.add(temp[0]);
		}
		PersistenceManager.getInstance().getAuthorizationPersistence().addRoleUsers(list, 4);
		return handleSuccess(mapping, context, "success");
	}
}
