/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.edu.zju.acm.onlinejudge.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

/** 
 * MyEclipse Struts
 * Creation date: 08-21-2008
 * 
 * XDoclet definition:
 * @struts.form name="importUserForm"
 */
public class ImportUserForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** userinfo property */
	private FormFile userinfo;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the userinfo.
	 * @return String
	 */
	public FormFile getUserinfo() {
		return userinfo;
	}

	/** 
	 * Set the userinfo.
	 * @param userinfo The userinfo to set
	 */
	public void setUserinfo(FormFile userinfo) {
		this.userinfo = userinfo;
	}
}